# Generated by Django 3.1.4 on 2020-12-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201230_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dscription',
            new_name='description',
        ),
    ]
