# Generated by Django 3.1.4 on 2020-12-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priduct',
            new_name='product',
        ),
    ]
